### ISSUE TITLE
Hosting online? Storing books in external location?

### ISSUE THREAD

**Issue by Aspiring-Writer** [puhoy/lspace#21]
First off, I just want to say thank you to the developer for creating this project. I have spent quite some time looking for something that could replace [COPS](https://github.com/seblucas/cops), and I was starting to think I would have to start from scratch and figure out how to build my own. I was quite happy to find this project because Python is the language I was thinking of learning for this hobby project of mine, and I don't have to start from scratch either!

Now, on to my actual "issues." Is it possible to (1) host this project on an online web server to view your books from anywhere (GitHub, Heroku, Netlify), and (2) how would we access the files from an external location?

P.S. I hope that sometime in the future these issues can be resolved and that I can contribute to this project.

**Comment by puhoy** [comment]
Hey, thanks for your interest in the project!

For your first question: I did not really intend lspace to be run on an actual server somewhere - i just wanted my tiny ebook manager to be able to easily share books sometimes. 
But the built-in webserver thingy is based on [flask](https://flask.palletsprojects.com/) and served with [gunicorn](https://gunicorn.org/), which should be pretty performant. The only thing different from a "production" setup would be that gunicorn serves the actual ebook files as well - in the real world you would probably let a "real" webserver like nginx do stuff like that, as it is more optimized for serving static files. But as long as you dont have a high load on your server, it should be fine as it is.

That being said, i would say: you could, in theory, run this on a server somewhere - for example, write a systemd unit to make sure its started when the server boots, restrict access to localhost with `lspace web --host=127.0.0.1 --port=5000` and hook it up to nginx (or some other webserver) as a proxy to add a https certificate, and maybe have simple access control with a `.htpasswd` file. (...or something in that direction. I can sketch this out some more if you want.)

About your second question, accessing external files: I dont really see this as a task for lspace. Its built in a way that it only deals with the local file system, and it would be pretty hard to change that.
What kind of external location do you have in mind? Maybe you could mount it with FUSE, and make it look like local files..?

Also, thank you for mentioning COPS. Serving OPDS seems like an interesting feature to have in lspace! I did not know about this standard! :)

**Comment by Aspiring-Writer** [comment]
I think you could [run this on Heroku](https://stackabuse.com/deploying-a-flask-application-to-heroku/) since it uses flask and gunicorn. I do plan on keeping it low-key and just for myself to access.

Furthermore, I was looking into Python tutorials and I came across [this video about setting up a full Python website with flask](https://youtu.be/dam0GPOAvVI). The video showed how to add user authentication, and I think that would be good for my purposes and to keep out unwanted visitors.

As for accessing external files, originally I was referring to cloud services (e.g. Dropbox, Google Drive, MEGA), however now I would rather upload the e-book files to a private GitHub repo and access them with lspace. I'm not sure how lspace will react to it, but I think that it shouldn't be a problem as long as the repo is named "library" and can be accessed by the server.

As for OPDS, no problem ;) and good luck!

**Comment by puhoy** [comment]
Closing this, since i have no plans for adding external storage or authentication. I opened a new issue for OPDS though.
